### ISSUE TITLE
Cannot initialize in 8.0.9

### ISSUE THREAD

**Issue by jordanbcooper** [starkandwayne/shield-boshrelease#127] opened 2018-06-04 19:11 UTC
Initializing shield in 8.0.9 gives "Failed to load resource: the server responded with a status of 400 (Bad Request)"

**Comment by daviddob** [comment] 2018-06-04 20:21
Can you provide some more information? (How you are initializing SHIELD - webUI/CLI - relevant params, logs, etc)

**Comment by jordanbcooper** [comment] 2018-06-04 20:33
My apologies, I certainly can. 

Initializing using web cli. Works fine in 8.0.8. Nothing special is set in the manifest, just bosh (2) interpolated manfiest with the core job (no addons). The only logs I'm able to get are from chrome console telling me what I sent in my inital comment.

**Comment by jordanbcooper** [comment] 2018-06-11 14:25
Yes, I meant the web ui. Still no luck on my end.

**Comment by jhunt** [comment] 2018-06-13 14:56
I believe we found the root cause of this.  Fix has been pushed to master and we are testing locally in a few environments.  Will cut 8.0.10 soon-ish (hopefully today) so you can give that a whirl.

**Comment by jordanbcooper** [comment] 2018-06-13 16:13
Thanks James, looking forward to that.

**Comment by jhunt** [comment] 2018-06-14 14:39
8.0.10 BOSH release is out: https://github.com/starkandwayne/shield-boshrelease/releases/tag/v8.0.10

**Closed** 2018-06-14 20:05 UTC
