### ISSUE TITLE
Fail to upgrade to v8.0.9.

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield-boshrelease#130] opened 2018-06-12 01:42 UTC
I failed to upgrade from v8.0.8 to v8.0.9 like below steps.

**Step 1.**
I deploy SHIELD using shield-bosh release 8.0.8.
I init SHIELD and input master password. It worked well.
I make some jobs, targets and etc.

**Step 2.**
I upgrade SHIELD using shield-bosh release 8.0.9.
I use same manifest and just modify release and deploy.

**Step 3.**
I input same master password made in Step 1 to unlock SHIELD.
But it fail with "Unable tp unlock the SHIELD Core" message.

**Step 4.**
I downgrade SHIELD using shield-bosh release 8.0.8 again.
I success to unlock SHIELD with same master password made in Step 1.

For all step, same disk is attached to shield vm.

I want to keep my SHIELD data and just upgrade shield-bosh release version.
How can I solve this problem?

**Comment by jhunt** [comment] 2018-06-13 14:56
I believe we found the root cause of this.  Fix has been pushed to master and we are testing locally in a few environments.  Will cut 8.0.10 soon-ish (hopefully today) so you can give that a whirl.

**Comment by jhunt** [comment] 2018-06-14 14:40
8.0.10 BOSH release is out: https://github.com/starkandwayne/shield-boshrelease/releases/tag/v8.0.10

Can you give 8.0.8 → 8.0.10 a shot, @eujungkim ?

**Comment by jordanbcooper** [comment] 2018-06-14 14:53
Was able to successfully initialize. Thanks @jhunt !

**Comment by jhunt** [comment] 2018-06-14 20:03
Excellent!

**Closed by jhunt** 2018-06-14 20:03 UTC

**Comment by eujungkim** [comment] 2018-06-15 01:48
@jhunt I'll try soon and give a feedback.  Thank you for you quick release.

**Comment by jhunt** [comment] 2018-06-15 14:42
If it doesn't work for you, feel free to reopen the ticket.
