### ISSUE TITLE
How to recovery SHIELD itself?

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield-boshrelease#128] opened 2018-06-06 23:41 UTC
I install SHIELD using shield-boshrelease v8.0.8.

Can I get the latest guide how to backup and recovery SHIELD itself?

**Comment by jhunt** [comment] 2018-06-09 13:27
I don't know that we have it documented on the website yet.  I'll try to pull together a guide on https://shieldproject.io/docs and then blog about it somewhere.

**Comment by jhunt** [comment] 2018-06-09 13:31
This is a duplicate of https://github.com/starkandwayne/shield/issues/413.

**Closed by jhunt** 2018-06-09 13:31 UTC
